baseURL = "https://djangocamera.netlify.app/"
languageCode = "fr-fr"
DefaultContentLanguage = "fr"
title = "Surveillance camera avec raspberry, mjpg-streamer, Django et Apache"
theme = "hugo-geekdoc"

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableGitInfo = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
  tag = "tags"

[params]    
# (Optional, default static/brand.svg) Set the path to a logo for the Geekdoc
# relative to your 'static/' folder.
geekdocLogo = "logo/logo_camera.svg"

# (Optional, default false) Render menu from data file im 'data/menu/main.yaml'.
geekdocMenuBundle = true

# (Optional, default true) Display a "Back to top" link in the site footer.
geekdocBackToTop = true
