baseURL = "djangocamera.netlify.app"
languageCode = "fr"
title = "Surveillance camera avec raspberry, mjpg-streamer, Django et Apache"
theme = "hugo-geekdoc"

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[params]    
# (Optional, default static/brand.svg) Set the path to a logo for the Geekdoc
# relative to your 'static/' folder.
geekdocLogo = "logo/logo_camera.svg"

# (Optional, default false) Render menu from data file im 'data/menu/main.yaml'.
geekdocMenuBundle = true


